In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6,7,8])#create 1D array
print(arr1)#show the 1D array list

[1 2 3 4 5 6 7 8]


In [5]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])#create 2D array
print(arr2)#shoe the 2D array result in list

[[1 2 3 4]
 [5 6 7 8]]
