In [1]:
import numpy as np

In [2]:
arr1=np.array([220,230,240])#create 1D array
print(arr1)#show the 1d array result in list

[220 230 240]


In [3]:
arr2=np.array([
    [320,330,340],
    [420,430,440]
                  ])#create 2D array
print(arr2)#show the 2D array result in list

[[320 330 340]
 [420 430 440]]


In [5]:
#check the Shape and Dimension
print(arr2.shape)#show the array shape like row and column numbers
print(arr2.ndim)#show the array dimension 

(2, 3)
2


In [8]:
#check the axis
print(np.sum(arr2,axis=0))#0 means column sums
print(np.sum(arr2,axis=1))#1 means row sums

[740 760 780]
[ 990 1290]


In [13]:
#create basics operation
arr3=arr1+10#add array1 all element and create new array3
arr4=arr1*2#multiple 2 all element with arr1 and create new array4
arr5=arr1+np.array([100,200,300])#arr1 previous array and create new array then all element add and new array5
print("arr3=",arr3)#create new arrry3
print("arr4=",arr4)#create new array4
print("arr5=",arr5)#create new array5

arr3= [230 240 250]
arr4= [440 460 480]
arr5= [320 430 540]
