In [1]:
import numpy as np

In [2]:
arr1=np.array([10,20,30,40])#create 1D array
print(arr1)#show the 1D array result in list

[10 20 30 40]


In [10]:
arr2=np.array([
    [50,60,70,80],
    [90,100,110,120]
                     ])#create 2D array
print(arr2)#show the 2D array result in list

[[ 50  60  70  80]
 [ 90 100 110 120]]


In [8]:
#create shape and axis
print(arr2.shape)#row and column shows
print(arr2.ndim)#jsut show the dimension 

(2, 4)
2


In [15]:
#create the array axis
print(np.sum(arr2,axis=0))#column axis
print(np.sum(arr2,axis=1))#row axis

[140 160 180 200]
[260 420]
